const state={news:[],aiBriefings:null,aiStatus:null,type:'all',category:'all',period:7,query:'',sort:'importance',visible:18};
const $=s=>document.querySelector(s);
const elements={grid:$('#newsGrid'),template:$('#newsCardTemplate'),empty:$('#emptyState'),loadMore:$('#loadMoreButton'),updatedAt:$('#updatedAt'),totalCount:$('#totalCount'),dailyCount:$('#dailyCount'),koreaCount:$('#koreaCount'),youtubeCount:$('#youtubeCount'),search:$('#searchInput'),sort:$('#sortSelect'),refresh:$('#refreshButton'),reset:$('#resetButton'),resultInfo:$('#resultInfo'),brief:$('#briefText'),sourceStatus:$('#sourceStatusList'),briefingPeriod:$('#briefingPeriod'),marketSignal:$('#marketSignal'),marketOutlookTitle:$('#marketOutlookTitle'),marketOutlookSummary:$('#marketOutlookSummary'),marketDrivers:$('#marketDrivers'),buyRecommendations:$('#buyRecommendations'),sellRecommendations:$('#sellRecommendations'),riskWatchList:$('#riskWatchList')};
const dateFormatter=new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const POSITIVE_TERMS={'금리 인하':5,'수주':4,'흑자':4,'사상 최대':4,'실적 개선':4,'상향':3,'수출 증가':3,'투자 확대':3,'증설':3,'회복':2,'반등':2,'성장':2,'호조':2,'급등':1};
const NEGATIVE_TERMS={'금리 인상':-5,'상장폐지':-6,'거래정지':-6,'파산':-6,'부도':-6,'유상증자':-4,'전환사채':-3,'적자':-4,'실적 악화':-4,'하향':-3,'경기침체':-4,'급락':-3,'규제 강화':-3,'감산':-2,'둔화':-2,'우려':-1};
const MARKET_TERMS={'기준금리':2,'금리 인하':4,'금리 인상':-4,'환율 급등':-3,'원화 강세':2,'원화 약세':-2,'수출 증가':3,'수출 감소':-3,'물가 안정':2,'물가 상승':-2,'경기 회복':3,'경기침체':-4,'코스피 상승':2,'코스피 하락':-2};
const STOCK_RULES=[
{name:'삼성전자',code:'005930',keywords:['삼성전자','반도체','메모리','파운드리','HBM'],sector:'반도체'},
{name:'SK하이닉스',code:'000660',keywords:['SK하이닉스','하이닉스','HBM','메모리 반도체'],sector:'반도체'},
{name:'현대차',code:'005380',keywords:['현대차','자동차 수출','전기차','하이브리드'],sector:'자동차'},
{name:'기아',code:'000270',keywords:['기아','자동차 수출','전기차','하이브리드'],sector:'자동차'},
{name:'한화에어로스페이스',code:'012450',keywords:['한화에어로스페이스','방산 수출','방위산업','K9','천무'],sector:'방산'},
{name:'HD현대중공업',code:'329180',keywords:['HD현대중공업','조선 수주','선박 수주','LNG선'],sector:'조선'},
{name:'삼성중공업',code:'010140',keywords:['삼성중공업','조선 수주','선박 수주','LNG선'],sector:'조선'},
{name:'POSCO홀딩스',code:'005490',keywords:['POSCO홀딩스','포스코','철강','리튬','이차전지 소재'],sector:'소재'},
{name:'LG에너지솔루션',code:'373220',keywords:['LG에너지솔루션','배터리','이차전지','전기차 수요'],sector:'이차전지'},
{name:'삼성SDI',code:'006400',keywords:['삼성SDI','배터리','이차전지','전기차 수요'],sector:'이차전지'},
{name:'NAVER',code:'035420',keywords:['네이버','NAVER','플랫폼','AI 서비스','광고 경기'],sector:'인터넷'},
{name:'카카오',code:'035720',keywords:['카카오','플랫폼 규제','광고 경기','인터넷 플랫폼'],sector:'인터넷'},
{name:'KB금융',code:'105560',keywords:['KB금융','은행주','은행 실적','순이자마진','주주환원'],sector:'금융'},
{name:'신한지주',code:'055550',keywords:['신한지주','은행주','은행 실적','순이자마진','주주환원'],sector:'금융'},
{name:'현대건설',code:'000720',keywords:['현대건설','해외수주','재건축','SOC','건설 수주'],sector:'건설'},
{name:'대우건설',code:'047040',keywords:['대우건설','해외수주','재건축','SOC','건설 수주'],sector:'건설'}
];
const RISK_RULES=[['고금리',['금리 인상','고금리','긴축']],['환율 변동',['환율 급등','원화 약세','달러 강세']],['경기 둔화',['경기침체','둔화','소비 감소']],['기업 자금조달',['유상증자','전환사채','회사채']],['상장·신용 위험',['상장폐지','거래정지','부도','파산']],['부동산 위험',['미분양','PF 부실','프로젝트파이낸싱']],['정책·규제',['규제 강화','공매도','관세']]];
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function safeUrl(v){try{const u=new URL(String(v));return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function hoursSince(v){return(Date.now()-new Date(v).getTime())/3600000}
function filteredNews(){const max=state.period*24,q=state.query.trim().toLowerCase();return state.news.filter(i=>{const type=i.type||'news';const text=`${i.title} ${i.description||''} ${i.source||''}`.toLowerCase();return i.country==='대한민국'&&(state.type==='all'||type===state.type)&&(state.category==='all'||i.category===state.category)&&hoursSince(i.published_at)<=max&&(!q||text.includes(q))}).sort((a,b)=>state.sort==='latest'?new Date(b.published_at)-new Date(a.published_at):(b.importance_score-a.importance_score)||(new Date(b.published_at)-new Date(a.published_at)))}
function scoreText(text,terms){const normalized=text.toLowerCase();return Object.entries(terms).reduce((sum,[term,weight])=>sum+(normalized.includes(term.toLowerCase())?weight:0),0)}
function periodNews(){return state.news.filter(n=>n.country==='대한민국'&&hoursSince(n.published_at)<=state.period*24)}
function articleScore(item){const text=`${item.title} ${item.description||''}`;return scoreText(text,POSITIVE_TERMS)+scoreText(text,NEGATIVE_TERMS)}
function renderSummary(){const domestic=state.news.filter(n=>n.country==='대한민국');elements.totalCount.textContent=domestic.length.toLocaleString('ko-KR');elements.dailyCount.textContent=domestic.filter(n=>hoursSince(n.published_at)<=24).length.toLocaleString('ko-KR');elements.koreaCount.textContent=domestic.filter(n=>(n.type||'news')==='news').length.toLocaleString('ko-KR');elements.youtubeCount.textContent=domestic.filter(n=>(n.type||'news')==='youtube').length.toLocaleString('ko-KR');const ai=state.aiStatus?.status==='ok'?` · AI 브리핑 ${state.aiStatus.model||''}`:'';elements.brief.textContent=`최근 24시간 ${elements.dailyCount.textContent}건 · 유튜브 ${elements.youtubeCount.textContent}건을 수집했습니다${ai}.`}
function renderNews(){const result=filteredNews(),visible=result.slice(0,state.visible);elements.grid.innerHTML='';for(const item of visible){const f=elements.template.content.cloneNode(true),card=f.querySelector('.news-card'),type=item.type||'news';card.classList.add(type);const thumbLink=f.querySelector('.thumbnail-link'),thumb=f.querySelector('.news-thumbnail');thumbLink.href=item.url;if(item.thumbnail){thumb.src=item.thumbnail;thumb.alt=`${item.title} 썸네일`}f.querySelector('.type-badge').textContent=type==='youtube'?(item.summary_source==='transcript'?'YouTube 요약':'YouTube 설명'):'NEWS';f.querySelector('.country-badge').textContent=item.collection_label||'대한민국';f.querySelector('.category-badge').textContent=item.category;const imp=f.querySelector('.importance-badge');imp.textContent=item.importance_score>=80?'핵심':item.importance_score>=60?'주요':'일반';if(item.importance_score<60)imp.hidden=true;const link=f.querySelector('.news-link');link.textContent=item.title;link.href=item.url;const description=f.querySelector('.news-description');description.textContent=item.description||'원문에서 자세한 내용을 확인하세요.';if(type==='youtube'&&item.summary_source==='transcript')description.setAttribute('aria-label','영상 자막 기반 자동 요약');f.querySelector('.news-source').textContent=item.source||'출처 미상';const t=f.querySelector('.news-date');t.dateTime=item.published_at;t.textContent=dateFormatter.format(new Date(item.published_at));elements.grid.appendChild(f)}elements.empty.hidden=result.length>0;elements.loadMore.hidden=result.length<=state.visible;elements.resultInfo.textContent=`${state.period===1?'24시간':state.period+'일'} 기준 · ${result.length.toLocaleString('ko-KR')}건 표시`}
function buildStockSignals(items){return STOCK_RULES.map(stock=>{const matched=items.filter(item=>{const text=`${item.title} ${item.description||''}`.toLowerCase();return stock.keywords.some(k=>text.includes(k.toLowerCase()))});if(!matched.length)return null;const weighted=matched.map(item=>({item,score:articleScore(item)+(item.importance_score||0)/25}));const total=weighted.reduce((sum,x)=>sum+x.score,0);const best=[...weighted].sort((a,b)=>Math.abs(b.score)-Math.abs(a.score)||(b.item.importance_score||0)-(a.item.importance_score||0))[0];return{...stock,score:total,count:matched.length,article:best.item};}).filter(Boolean).sort((a,b)=>Math.abs(b.score)-Math.abs(a.score))}
function recommendationMarkup(item,type){const action=type==='buy'?'관심·분할매수 검토':'비중 축소·매도 검토';const basis=item.score>0?'긍정':'부정';return `<article class="recommendation-item"><div><strong>${item.name}</strong><span>${item.code} · ${item.sector}</span></div><span class="recommendation-action ${type}">${action}</span><p>${basis} 신호 ${item.count}건 · 대표 근거: <a href="${item.article.url}" target="_blank" rel="noopener noreferrer">${item.article.title}</a></p></article>`}
function evidenceMarkup(evidence=[]){return evidence.map(e=>`<a href="${safeUrl(e.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(e.title)}</a>`).join('')}
function aiCandidateMarkup(item,type){const action=type==='buy'?'관심·분할매수 검토':'비중 축소·매도 검토';const evidence=(item.evidence||[])[0];return `<article class="recommendation-item"><div><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.code||'')} ${item.sector?'· '+escapeHtml(item.sector):''}</span></div><span class="recommendation-action ${type}">${action}</span><p>${escapeHtml(item.reason)}${item.risk?`<br><b>반대 시나리오:</b> ${escapeHtml(item.risk)}`:''}${evidence?`<br><b>근거:</b> <a href="${safeUrl(evidence.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(evidence.title)}</a>`:''}</p></article>`}
function renderAiBriefing(brief){const cls=brief.signal==='긍정'?'positive':brief.signal==='경계'?'negative':'neutral';elements.marketSignal.className=`market-signal ${cls}`;elements.marketSignal.textContent=`AI ${brief.signal||'중립'} · 신뢰도 ${Number(brief.confidence||0)}%`;elements.marketOutlookTitle.textContent=brief.title||'AI 시장 브리핑';elements.marketOutlookSummary.textContent=brief.summary||'AI 분석 결과가 없습니다.';elements.marketDrivers.innerHTML=(brief.drivers||[]).length?(brief.drivers||[]).map(d=>`<div class="ai-driver"><span>${escapeHtml(d.sentiment)} 근거</span><strong>${escapeHtml(d.title)}</strong>${evidenceMarkup(d.evidence||[])}</div>`).join(''):'<span class="driver-empty">직접 확인 가능한 핵심 근거가 부족합니다.</span>';elements.buyRecommendations.innerHTML=(brief.buy_candidates||[]).length?brief.buy_candidates.map(x=>aiCandidateMarkup(x,'buy')).join(''):'<p class="result-info">뉴스와 직접 연결되는 매수 검토 종목이 없습니다.</p>';elements.sellRecommendations.innerHTML=(brief.sell_candidates||[]).length?brief.sell_candidates.map(x=>aiCandidateMarkup(x,'sell')).join(''):'<p class="result-info">뉴스와 직접 연결되는 축소 검토 종목이 없습니다.</p>';const tags=[...(brief.risks||[]),...(brief.checks||[]).map(x=>`확인: ${x}`)];elements.riskWatchList.innerHTML=(tags.length?tags:['특이 리스크 신호 없음']).map(r=>`<span>${escapeHtml(r)}</span>`).join('')}
function renderRuleBriefing(){const items=periodNews();if(!items.length){elements.marketSignal.className='market-signal neutral';elements.marketSignal.textContent='자료 부족';elements.marketOutlookTitle.textContent='분석할 뉴스가 없습니다.';elements.marketOutlookSummary.textContent='GitHub Actions 수집 결과를 확인하십시오.';elements.marketDrivers.innerHTML='';elements.buyRecommendations.innerHTML='<p class="result-info">추천 신호 없음</p>';elements.sellRecommendations.innerHTML='<p class="result-info">추천 신호 없음</p>';elements.riskWatchList.innerHTML='<span>자료 부족</span>';return}const scored=items.map(item=>({item,score:scoreText(`${item.title} ${item.description||''}`,MARKET_TERMS)+articleScore(item)}));const rawScore=scored.reduce((sum,x)=>sum+x.score*((x.item.importance_score||50)/50),0);const normalized=rawScore/Math.max(items.length,1);let signal='중립',signalClass='neutral',title='혼조세 가능성—업종별 선별 접근 필요';if(normalized>=1.2){signal='긍정';signalClass='positive';title='완만한 상승 우위—긍정 뉴스 업종 중심 접근'}else if(normalized<=-1.2){signal='경계';signalClass='negative';title='하방 위험 우위—현금 비중과 손실 관리 필요'}elements.marketSignal.className=`market-signal ${signalClass}`;elements.marketSignal.textContent=`규칙 ${signal}`;elements.marketOutlookTitle.textContent=title;const positiveCount=scored.filter(x=>x.score>0).length,negativeCount=scored.filter(x=>x.score<0).length;elements.marketOutlookSummary.textContent=`AI 분석을 사용할 수 없어 규칙 기반으로 대체했습니다. 분석 대상 ${items.length}건 중 긍정 신호 ${positiveCount}건, 부정 신호 ${negativeCount}건입니다.`;const drivers=[...scored].filter(x=>x.score!==0).sort((a,b)=>Math.abs(b.score)-Math.abs(a.score)||(b.item.importance_score||0)-(a.item.importance_score||0)).slice(0,3);elements.marketDrivers.innerHTML=drivers.length?drivers.map(x=>`<a href="${x.item.url}" target="_blank" rel="noopener noreferrer"><span>${x.score>0?'긍정':'부정'} 근거</span>${x.item.title}</a>`).join(''):'<span class="driver-empty">방향성이 뚜렷한 핵심 뉴스가 부족합니다.</span>';const stocks=buildStockSignals(items),buys=stocks.filter(x=>x.score>=2).slice(0,5),sells=stocks.filter(x=>x.score<=-2).slice(0,5);elements.buyRecommendations.innerHTML=buys.length?buys.map(x=>recommendationMarkup(x,'buy')).join(''):'<p class="result-info">뚜렷한 긍정 종목 신호가 없습니다.</p>';elements.sellRecommendations.innerHTML=sells.length?sells.map(x=>recommendationMarkup(x,'sell')).join(''):'<p class="result-info">뚜렷한 부정 종목 신호가 없습니다.</p>';const combined=items.map(i=>`${i.title} ${i.description||''}`).join(' ').toLowerCase(),risks=RISK_RULES.filter(([,keywords])=>keywords.some(k=>combined.includes(k.toLowerCase()))).map(([name])=>name);elements.riskWatchList.innerHTML=(risks.length?risks:['특이 리스크 신호 없음']).map(r=>`<span>${r}</span>`).join('')}
function renderInvestmentBriefing(){if(!elements.marketSignal)return;elements.briefingPeriod.textContent=state.period===1?'최근 24시간 기준':`최근 ${state.period}일 기준`;const brief=state.period===1?state.aiBriefings?.daily:state.aiBriefings?.weekly;if(brief&&state.aiBriefings?.analysis_type==='openai')renderAiBriefing(brief);else renderRuleBriefing()}
function renderSourceStatus(statuses=[]){if(!elements.sourceStatus)return;elements.sourceStatus.innerHTML='';if(!statuses.length){elements.sourceStatus.innerHTML='<p class="result-info">수집 상태 정보가 없습니다.</p>';return}for(const s of statuses){const item=document.createElement('article');item.className='source-status-item';const badges=[];badges.push(`<span class="status-badge ${s.status==='ok'?'ok':'fail'}">${s.status==='ok'?'정상':'실패'}</span>`);if(s.requires_auth)badges.push('<span class="status-badge auth">인증 필요</span>');if(s.restricted)badges.push('<span class="status-badge limited">자동수집 제한</span>');item.innerHTML=`<div class="source-status-head"><strong>${s.name}</strong><div>${badges.join('')}</div></div><p><b>현재 방식</b> ${s.label||'확인 불가'}</p><p><b>대체 방식</b> ${s.alternative||'없음'}</p>`;elements.sourceStatus.appendChild(item)}}
function resetAndRender(){state.visible=18;renderNews();renderInvestmentBriefing()}
function bind(container,key,dataKey,transform=v=>v){$(container).addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll(`${container} button`).forEach(x=>x.classList.remove('active'));b.classList.add('active');state[key]=transform(b.dataset[dataKey]);resetAndRender()})}
function setPeriod(period){state.period=period;document.querySelectorAll('#periodFilters button').forEach(b=>b.classList.toggle('active',Number(b.dataset.period)===period));document.querySelectorAll('#quickPeriods button').forEach(b=>b.classList.toggle('active',Number(b.dataset.quickPeriod)===period));resetAndRender()}
async function loadNews(){elements.updatedAt.textContent='불러오는 중';try{const r=await fetch(`data/news.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();state.news=(Array.isArray(p.news)?p.news:[]).filter(item=>item.country==='대한민국');state.aiBriefings=p.ai_briefings||null;state.aiStatus=p.ai_status||null;elements.updatedAt.textContent=p.updated_at?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(p.updated_at)):'업데이트 정보 없음';renderSummary();renderNews();renderInvestmentBriefing();renderSourceStatus(Array.isArray(p.source_status)?p.source_status:[])}catch(e){console.error(e);state.news=[];state.aiBriefings=null;state.aiStatus=null;elements.updatedAt.textContent='데이터 로드 실패';elements.empty.hidden=false;elements.empty.textContent='뉴스 데이터를 불러오지 못했습니다. GitHub Actions 실행 상태를 확인하세요.';renderInvestmentBriefing();renderSourceStatus([])}}
bind('#typeFilters','type','type');bind('#categoryFilters','category','category');bind('#periodFilters','period','period',Number);$('#quickPeriods').addEventListener('click',e=>{const b=e.target.closest('button');if(b)setPeriod(Number(b.dataset.quickPeriod))});elements.search.addEventListener('input',e=>{state.query=e.target.value;resetAndRender()});elements.sort.addEventListener('change',e=>{state.sort=e.target.value;resetAndRender()});elements.loadMore.addEventListener('click',()=>{state.visible+=18;renderNews()});elements.refresh.addEventListener('click',loadNews);elements.reset.addEventListener('click',()=>{state.type='all';state.category='all';state.query='';state.sort='importance';elements.search.value='';elements.sort.value='importance';['#typeFilters','#categoryFilters'].forEach(sel=>document.querySelectorAll(`${sel} button`).forEach((b,i)=>b.classList.toggle('active',i===0)));setPeriod(7)});loadNews();
