const state={news:[],type:'all',category:'all',period:7,query:'',sort:'importance',visible:18};
const $=s=>document.querySelector(s);
const elements={grid:$('#newsGrid'),template:$('#newsCardTemplate'),empty:$('#emptyState'),loadMore:$('#loadMoreButton'),updatedAt:$('#updatedAt'),totalCount:$('#totalCount'),dailyCount:$('#dailyCount'),koreaCount:$('#koreaCount'),youtubeCount:$('#youtubeCount'),search:$('#searchInput'),sort:$('#sortSelect'),refresh:$('#refreshButton'),reset:$('#resetButton'),resultInfo:$('#resultInfo'),brief:$('#briefText')};
const dateFormatter=new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
function hoursSince(v){return(Date.now()-new Date(v).getTime())/3600000}
function filteredNews(){const max=state.period*24,q=state.query.trim().toLowerCase();return state.news.filter(i=>{const type=i.type||'news';const text=`${i.title} ${i.description||''} ${i.source||''}`.toLowerCase();return i.country==='대한민국'&&(state.type==='all'||type===state.type)&&(state.category==='all'||i.category===state.category)&&hoursSince(i.published_at)<=max&&(!q||text.includes(q))}).sort((a,b)=>state.sort==='latest'?new Date(b.published_at)-new Date(a.published_at):(b.importance_score-a.importance_score)||(new Date(b.published_at)-new Date(a.published_at)))}
function renderSummary(){const domestic=state.news.filter(n=>n.country==='대한민국');elements.totalCount.textContent=domestic.length.toLocaleString('ko-KR');elements.dailyCount.textContent=domestic.filter(n=>hoursSince(n.published_at)<=24).length.toLocaleString('ko-KR');elements.koreaCount.textContent=domestic.filter(n=>(n.type||'news')==='news').length.toLocaleString('ko-KR');elements.youtubeCount.textContent=domestic.filter(n=>(n.type||'news')==='youtube').length.toLocaleString('ko-KR');elements.brief.textContent=`최근 24시간 ${elements.dailyCount.textContent}건 · 유튜브 ${elements.youtubeCount.textContent}건을 수집했습니다.`}
function renderNews(){const result=filteredNews(),visible=result.slice(0,state.visible);elements.grid.innerHTML='';for(const item of visible){const f=elements.template.content.cloneNode(true),card=f.querySelector('.news-card'),type=item.type||'news';card.classList.add(type);const thumbLink=f.querySelector('.thumbnail-link'),thumb=f.querySelector('.news-thumbnail');thumbLink.href=item.url;if(item.thumbnail){thumb.src=item.thumbnail;thumb.alt=`${item.title} 썸네일`}f.querySelector('.type-badge').textContent=type==='youtube'?'YouTube':'NEWS';f.querySelector('.country-badge').textContent='대한민국';f.querySelector('.category-badge').textContent=item.category;const imp=f.querySelector('.importance-badge');imp.textContent=item.importance_score>=80?'핵심':item.importance_score>=60?'주요':'일반';if(item.importance_score<60)imp.hidden=true;const link=f.querySelector('.news-link');link.textContent=item.title;link.href=item.url;f.querySelector('.news-description').textContent=item.description||'원문에서 자세한 내용을 확인하세요.';f.querySelector('.news-source').textContent=item.source||'출처 미상';const t=f.querySelector('.news-date');t.dateTime=item.published_at;t.textContent=dateFormatter.format(new Date(item.published_at));elements.grid.appendChild(f)}elements.empty.hidden=result.length>0;elements.loadMore.hidden=result.length<=state.visible;elements.resultInfo.textContent=`${state.period===1?'24시간':state.period+'일'} 기준 · ${result.length.toLocaleString('ko-KR')}건 표시`}
function resetAndRender(){state.visible=18;renderNews()}
function bind(container,key,dataKey,transform=v=>v){$(container).addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll(`${container} button`).forEach(x=>x.classList.remove('active'));b.classList.add('active');state[key]=transform(b.dataset[dataKey]);resetAndRender()})}
function setPeriod(period){state.period=period;document.querySelectorAll('#periodFilters button').forEach(b=>b.classList.toggle('active',Number(b.dataset.period)===period));document.querySelectorAll('#quickPeriods button').forEach(b=>b.classList.toggle('active',Number(b.dataset.quickPeriod)===period));resetAndRender()}
async function loadNews(){elements.updatedAt.textContent='불러오는 중';try{const r=await fetch(`data/news.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json();state.news=(Array.isArray(p.news)?p.news:[]).filter(item=>item.country==='대한민국');elements.updatedAt.textContent=p.updated_at?new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(p.updated_at)):'업데이트 정보 없음';renderSummary();renderNews()}catch(e){console.error(e);state.news=[];elements.updatedAt.textContent='데이터 로드 실패';elements.empty.hidden=false;elements.empty.textContent='뉴스 데이터를 불러오지 못했습니다. GitHub Actions 실행 상태를 확인하세요.'}}
bind('#typeFilters','type','type');bind('#categoryFilters','category','category');bind('#periodFilters','period','period',Number);$('#quickPeriods').addEventListener('click',e=>{const b=e.target.closest('button');if(b)setPeriod(Number(b.dataset.quickPeriod))});elements.search.addEventListener('input',e=>{state.query=e.target.value;resetAndRender()});elements.sort.addEventListener('change',e=>{state.sort=e.target.value;resetAndRender()});elements.loadMore.addEventListener('click',()=>{state.visible+=18;renderNews()});elements.refresh.addEventListener('click',loadNews);elements.reset.addEventListener('click',()=>{state.type='all';state.category='all';state.query='';state.sort='importance';elements.search.value='';elements.sort.value='importance';['#typeFilters','#categoryFilters'].forEach(sel=>document.querySelectorAll(`${sel} button`).forEach((b,i)=>b.classList.toggle('active',i===0)));setPeriod(7)});loadNews();